
const productos = [
    {
        nombreProducto: "Playera Casual",
        descripcionProducto: "Playera casual para hombre o mujer",
        colorProducto: "Rojo",
        tallaProducto: "XS",
        imagenProducto: "img-1.jpg",
        cantidadProducto: "5",
        categoriaId: 1,
        usuarioId: 2,
    },
    {
        nombreProducto: "Playera Casual",
        descripcionProducto: "Playera casual para hombre o mujer",
        colorProducto: "Azul",
        tallaProducto: "S",
        imagenProducto: "img-2.jpg",
        cantidadProducto: "7",
        categoriaId: 1,
        usuarioId: 3,
    },
    {
        nombreProducto: "Playera Casual",
        descripcionProducto: "Playera casual para hombre o mujer",
        colorProducto: "Verde",
        tallaProducto: "M",
        imagenProducto: "img-3.jpg",
        cantidadProducto: "2",
        categoriaId: 1,
        usuarioId: 2,
    },
    {
        nombreProducto: "Playera de Superheroes",
        descripcionProducto: "Playera de Batman para hombre o mujer",
        colorProducto: "Gris",
        tallaProducto: "XL",
        imagenProducto: "img-4.jpg",
        cantidadProducto: "4",
        categoriaId: 1,
        usuarioId: 4,
    },
    {
        nombreProducto: "Playera Deportiva",
        descripcionProducto: "Playera deportiva, máxima Duración",
        colorProducto: "Blanca con negro",
        tallaProducto: "M",
        imagenProducto: "img-5.jpg",
        cantidadProducto: "10",
        categoriaId: 1,
        usuarioId: 3,
    },
    {
        nombreProducto: "Pantalon de Mezclilla",
        descripcionProducto: "Pantalon de Mezclilla vaquero",
        colorProducto: "Azul",
        tallaProducto: "XL",
        imagenProducto: "img-7.jpg",
        cantidadProducto: "2",
        categoriaId: 2,
        usuarioId: 5,
    },
    {
        nombreProducto: "Pantalón entubado",
        descripcionProducto: "Pantalón entubado, amplio de cadera",
        colorProducto: "Negro",
        tallaProducto: "M",
        imagenProducto: "img-8.jpg",
        cantidadProducto: "6",
        categoriaId: 2,
        usuarioId: 1,
    },
    {
        nombreProducto: "Vestido casual",
        descripcionProducto: "Vestido casual, indicado para tardes frescas",
        colorProducto: "Rojo",
        tallaProducto: "S",
        imagenProducto: "img-9.jpg",
        cantidadProducto: "6",
        categoriaId: 4,
        usuarioId: 3,
    },
    {
        nombreProducto: "Vestido",
        descripcionProducto: "Vestido transparente tipo top",
        colorProducto: "Verde",
        tallaProducto: "M",
        imagenProducto: "img-10.jpg",
        cantidadProducto: "5",
        categoriaId: 4,
        usuarioId: 3,
    },
    {
        nombreProducto: "Vestido tradicional",
        descripcionProducto: "Bonito vestido tradicional",
        colorProducto: "Azul",
        tallaProducto: "M",
        imagenProducto: "img-11.jpg",
        cantidadProducto: "9",
        categoriaId: 4,
        usuarioId: 4,
    },
    {
        nombreProducto: "Chamarra deportiva",
        descripcionProducto: "Excelente chamarra para hacer ejercicio por las mañanas",
        colorProducto: "Negra",
        tallaProducto: "XL",
        imagenProducto: "img-12.jpg",
        cantidadProducto: "15",
        categoriaId: 3,
        usuarioId: 2,
    },
    {
        nombreProducto: "Sudadera",
        descripcionProducto: "Sudadera para mujer ideal para el frio.",
        colorProducto: "Rosa",
        tallaProducto: "S",
        imagenProducto: "img-13.jpg",
        cantidadProducto: "4",
        categoriaId: 3,
        usuarioId: 2,
    },
    {
        nombreProducto: "Sudadera de serie",
        descripcionProducto: "Bonita Sudadera de Friends.",
        colorProducto: "Roja",
        tallaProducto: "M",
        imagenProducto: "img-14.jpg",
        cantidadProducto: "2",
        categoriaId: 3,
        usuarioId: 4,
    },
    {
        nombreProducto: "Sudadera",
        descripcionProducto: "Bonita sudadera casual",
        colorProducto: "Blanca con Amarillo",
        tallaProducto: "S",
        imagenProducto: "img-15.jpg",
        cantidadProducto: "8",
        categoriaId: 3,
        usuarioId: 2,
    },
];

export default productos;